<?php

declare(strict_types=1);

namespace Cambis\Silverstan\ConfigurationResolver\Extension\PhpDoc;

use Cambis\Silverstan\FileFinder\FileFinder;
use Override;
use PHPStan\Cache\Cache;
use PHPStan\PhpDoc\StubFilesExtension;
use function sprintf;

/**
 * This extension will invalidate PHPStan's result cache when the Silverstripe config is updated.
 *
 * @todo this can likely be replaced once the following issue is resolved: https://github.com/phpstan/phpstan-symfony/issues/255.
 */
final readonly class ConfigCacheExtension implements StubFilesExtension
{
    public function __construct(
        private Cache $cache,
        private FileFinder $fileFinder
    ) {
    }

    #[Override]
    public function getFiles(): array
    {
        /**
         * @var ?string
         * @phpstan-ignore phpstanApi.method
         */
        $path = $this->cache->load($this->fileFinder->getConfigCacheKey(), 'v1');

        if ($path === null) {
            /** @phpstan-ignore phpstanApi.method */
            $this->cache->save(
                $this->fileFinder->getConfigCacheKey(),
                'v1',
                sprintf("<?php\n\ndeclare(strict_types = 1);\n\n/** AUTOGENERATED %s */\n", $this->fileFinder->getConfigCacheKey())
            );

            /**
             * @var string
             * @phpstan-ignore phpstanApi.method
             */
            $path = $this->cache->load($this->fileFinder->getConfigCacheKey(), 'v1');
        }

        return [$path];
    }
}
