name: End to end 🥚 ➡️ 🐔

on:
  push:
    branches:
      - main
      - feature/silverstripe-config-1-x-support

env:
  # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
  COMPOSER_ROOT_VERSION: dev-main

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - directory: e2e/basic-app
            php-version: 8.1
            framework-version: 5.3
            cms-version: 5.3
          - directory: e2e/basic-app
            php-version: 7.4
            framework-version: 4.13
            cms-version: 4.13
          - directory: e2e/basic-module
            php-version: 8.1
            framework-version: 5.3
            cms-version: 5.3
    steps:
      # Build source code
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          coverage: none

      - uses: ramsey/composer-install@v2

      # Downgrade to PHP 7.4
      - run: vendor/bin/rector process config rules src --config build/rector-downgrade-php-74.php --ansi --no-diffs

      # Copy composer
      - run: cp build/composer-php-74.json composer.json

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      # Reinstall to clear out any unwanted dependencies
      - run: rm -rf vendor composer.lock

      # - uses: ramsey/composer-install@v2
      #   with:
      #     dependency-versions: highest

      - if: ${{ matrix.framework-version }} && ${{ matrix.cms-version }}
        run: composer require php:^${{ matrix.php-version }} silverstripe/framework:^${{ matrix.framework-version }} silverstripe/cms:^${{ matrix.cms-version }}
        working-directory: ${{ matrix.directory }}

      - if: ${{ matrix.framework-version }} && ${{ !matrix.cms-version }}
        run: composer require php:^${{ matrix.php-version }} silverstripe/framework:^${{ matrix.framework-version }}
        working-directory: ${{ matrix.directory }}

      # Set up e2e directory
      - uses: ramsey/composer-install@v2
        with:
          working-directory: ${{ matrix.directory }}
      
      # Run phpstan on the e2e directory
      - run: vendor/bin/phpstan analyse --configuration=phpstan.neon.dist
        working-directory: ${{ matrix.directory }}
